{
 "title": "Ruuvitag example dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Instructions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
     "content": "\n# Ruuvitag Grafana dashboard template\n\nExample assumes we relabel each sensor hardware address with\nid, name and location so they are easier to present with dashboards.\nYou may choose different labels, but then the example dashboard may\nneed adjustment too.\n\n```yaml\n  - job_name: 'ruuvi-prometheus'\n    static_configs:\n      - targets: ['ruuvi-prometheus:9521']\n    metric_relabel_configs:\n      # ... id and name relabel config for each sensor\n      - source_labels: ['device']\n        target_label: 'id'\n        regex: 'e7:37:3b:37:d9:74'\n        replacement: '2'\n      - source_labels: ['id']\n        target_label: 'name'\n        regex: '2'\n        replacement: 'garage'\n      # Map location based on id\n      - source_labels: ['id']\n        regex: '2|3|5|6|7|9'\n        target_label: 'location'\n        replacement: 'indoors'\n      - source_labels: ['id']\n        regex: '1|4'\n        target_label: 'location'\n        replacement: 'outdoors'\n```\n\n\n"
    }
   ]
  },
  { "title": "Example panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "ruuvi_temperature_celsius\n", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Air pressure",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "expr": "ruuvi_pressure_hpa{location=\"ulkona\"}\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Relative humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "ruuvi_humidity_ratio", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "ruuvi_battery_volts", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "RSSI signal strength",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(ruuvi_rssi_dbm[15m])\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received measurements",
   "type": "graph",
   "description": "This attempts to visualize how many measurements are lost due to radio level. Requires RAWv2 format frames in tags (upgrade firmware, enable RAW mode).",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(ruuvi_frames_total[5m]) / increase(ruuvi_seqno_current[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Ruuvi protocol version",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    { "expr": "ruuvi_format" },
    {
     "expr": "(15*60) / increase(ruuvi_seqno_current[15m])"
    }
   ]
  },
  {
   "title": "Measurements received interval",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "1/rate(ruuvi_frames_total[15m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Transmit interval over time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "1/rate(ruuvi_seqno_current[30m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}